// AC-8: package generated pages into a downloadable .zip.
// Pages are saved as index.html, services.html, gallery.html, contact.html, about.html.

import JSZip from "jszip";
import { GeneratedPage, PageKey } from "./types";

const FILENAME: Record<PageKey, string> = {
  home: "index.html",
  services: "services.html",
  gallery: "gallery.html",
  contact: "contact.html",
  about: "about.html",
};

const README = (businessName: string) => `# ${businessName} — generated website

Generated by the AI Website Generator (Finn-loop Issue #1).

## Files
- index.html — Home
- services.html — Services
- gallery.html — Gallery
- contact.html — Contact
- about.html — About

Open index.html in a browser to view the site. All pages link to each other.
`;

export async function buildZip(pages: GeneratedPage[]): Promise<Buffer> {
  const zip = new JSZip();
  const folder = zip.folder("site") ?? zip;
  for (const p of pages) {
    folder.file(FILENAME[p.key], p.html);
  }
  const businessName =
    pages.find((p) => p.key === "home")?.title || "website";
  folder.file("README.md", README(businessName));
  const out = await zip.generateAsync({ type: "nodebuffer" });
  return out as Buffer;
}

export { FILENAME };
